### ISSUE TITLE
Link change needs updating

### ISSUE THREAD

**Issue by Foxache** [Batlez/ChatGPT-Jailbroken#1]
**Fix:**

// ==UserScript==
// @name         ChatGPT Jailbroken! Use it for whatever
// @namespace    https://chatgpt.com/
// @version      1.1
// @description  ChatGPT Jailbroken! Includes FREE GPT-4
// @author       Batlez
// @license      MIT
// @match        https://chatgpt.com/*
// @grant        GM_addStyle
// @downloadURL https://update.greasyfork.org/scripts/487193/ChatGPT%20Jailbroken%21%20Use%20it%20for%20whatever.user.js
// @updateURL https://update.greasyfork.org/scripts/487193/ChatGPT%20Jailbroken%21%20Use%20it%20for%20whatever.meta.js
// ==/UserScript==

// Project Update

**Comment by Batlez** [comment]
Fixed
